---
- hosts: localhost
  gather_facts: false
  remote_user: ubuntu
  tasks:
    - name: Download Tomcat
      get_url: 
        url: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.22_7.tar.gz
        dest: /home/ubuntu/OpenJDK11U-jdk_x64_linux_hotspot_11.0.22_7.tar.gz
    
    - name: Extract archive
      unarchive:
        src: /home/ubuntu/OpenJDK11U-jdk_x64_linux_hotspot_11.0.22_7.tar.gz
        dest: /home/ubuntu
        remote_src: yes

   
   